# Generated by Django 3.2.9 on 2022-01-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20220104_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='teacher_department',
        ),
    ]
