# Generated by Django 3.2.9 on 2022-01-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_department_teacher_teacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_department',
            new_name='deptt',
        ),
    ]
