# Generated by Django 3.2.9 on 2022-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_name_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='for_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
