# Generated by Django 3.2.9 on 2022-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220106_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='section',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='batch_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
