# Generated by Django 3.2.9 on 2022-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_of_attendances_granted',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='no_of_attendances_possible',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
