# Generated by Django 3.2.9 on 2021-12-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211206_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.DO_NOTHING, to='user.role'),
        ),
    ]
