# Generated by Django 3.2.9 on 2021-12-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211206_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='user.Role'),
        ),
    ]
